version: "3.9"
services:
  postgres:
    container_name: ${CONTAINER_DB_NAME}
    image: postgres:16.1-alpine3.18
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 10s
      timeout: 10s
      retries: 30
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - my_network

  app:
    container_name: app
    ports:
      - '8000:8000'
    command: sh -c "alembic upgrade head && python app/main.py"
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my_network

volumes:
  fastapi_app:

networks:
  my_network:
    driver: bridge
